version: '2'
services:
  thrift:
    image: thrift:0.9.2
    volumes:
      - .:/data
    working_dir: /data
    command: thrift --gen rb example.thrift
  bundle:
    image: ruby:2.3
    volumes:
      - .:/data
    working_dir: /data
    command: bundle package --all
  test:
    build:
      context: .
    volumes:
      - .:/usr/src/app
  server:
    build:
      context: .
    command: ruby ./start-server.rb 9090
  ci:
    build:
      context: .
    volumes:
      - .:/usr/src/app